import 'dart:async';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:permission_handler/permission_handler.dart';
// import 'package:firebase_core/firebase_core.dart';
// import 'package:firebase_crashlytics/firebase_crashlytics.dart';
import 'presentation/app.dart';
import 'core/utils/file_logger.dart';

void main() async {
  runZonedGuarded(
    () async {
      WidgetsFlutterBinding.ensureInitialized();
      await FileLogger.init();

      // 1. Firebase Initialization (Optional check)
      try {
        // Note: DefaultFirebaseOptions is generated by flutterfire CLI
        // If it exists, initialize Firebase. Otherwise, we still catch errors.
        // await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
        // FlutterError.onError = FirebaseCrashlytics.instance.recordFlutterFatalError;
      } catch (e) {
        FileLogger.log("Firebase Init skipped or failed: $e");
      }

      // 2. Request Bluetooth permissions on startup
      await [
        Permission.bluetoothScan,
        Permission.bluetoothConnect,
        Permission.location,
      ].request();

      // 3. Full screen immersive mode
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.edgeToEdge);
      SystemChrome.setSystemUIOverlayStyle(
        const SystemUiOverlayStyle(
          statusBarColor: Colors.transparent,
          systemNavigationBarColor: Colors.transparent,
        ),
      );

      runApp(const ProviderScope(child: LastMileTrackerApp()));
    },
    (error, stack) {
      FileLogger.log("UNCAUGHT ERROR: $error\n$stack");
      // FirebaseCrashlytics.instance.recordError(error, stack, fatal: true);
    },
  );
}
